# numpy fast tutorial

In [ ]:
import numpy as np

In [3]:
x = np.array([[1, 2], [3, 4],[5, 6], [7, 8]])
print(x)
print(x[3][1])и
print(x[1])

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
8
[3 4]


In [6]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


In [13]:
# матрица 10 на 10 
Z = с
print(Z)
zmin, zmax, zmean = Z.min(), Z.max(), Z.mean()
print(zmin, zmax, zmean)

[[0.28096964 0.06004366 0.20992832 0.75932666 0.67784197 0.58361786
  0.88658484 0.71912684 0.78979891 0.46162299]
 [0.97667214 0.3689551  0.39848762 0.75582845 0.51491788 0.95554649
  0.3072814  0.65112576 0.15015562 0.88793037]
 [0.24940723 0.84728963 0.29093794 0.43658263 0.68291086 0.01510025
  0.10089454 0.0852359  0.61513296 0.63522127]
 [0.14786877 0.70513257 0.12785211 0.72378057 0.06409383 0.64341836
  0.96195439 0.27310421 0.03922872 0.53209212]
 [0.61730987 0.69536013 0.66546048 0.49332669 0.0501125  0.5281498
  0.71572293 0.26598596 0.37447952 0.0244901 ]
 [0.02899652 0.15590038 0.87467205 0.6406044  0.09157425 0.68821545
  0.5016503  0.91205951 0.21237471 0.29444785]
 [0.72955616 0.80681083 0.55067189 0.408118   0.72848727 0.0115167
  0.25865325 0.42804497 0.07927187 0.95421824]
 [0.23111521 0.81738213 0.83304028 0.33911449 0.98882975 0.70555408
  0.00313934 0.16320274 0.82575275 0.19210851]
 [0.2165468  0.22661903 0.63731946 0.33643806 0.17423061 0.9018967
  0.23657576 0.

In [148]:
A = np.arange(25) 
# print(A)
A = A.reshape(5, 5) # модификация в 5 на 5, должно быть кратно 5
# print(A)
A[[0, 1]] = A[[1, 0]]
# print(A)


[[0 1 2 3 4]]


In [38]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3*0.1)
print(3*0.1) #? 
print(3/10)

nan
False
False
nan
False
0.30000000000000004
0.3


In [44]:
from random import randint
arr = np.array([randint(0, 100) for i in range(10)])
print(np.sort(arr))

[  5   8  39  44  51  55  59  65  97 100]


In [112]:
# 1.3.1
# заполнили массив 8 на 8 нулями 
arr = np.zeros((8,8),dtype=int)
# каждый 2 массив начиная с первого каждый 2 элемент = 1
arr[1::2,::2] = 1 
# каждый 2 массив начиная с нулевого каждый 2 элемент начиная с первого = 1
arr[::2,1::2] = 1
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [126]:
# 1.3.2
np.full((5,5), np.arange(5))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [128]:
# 1.3.3
np.random.random((3, 3, 3))

array([[[0.20109083, 0.57820445, 0.38111258],
        [0.89391493, 0.99417227, 0.43350802],
        [0.67402613, 0.59880944, 0.36270216]],

       [[0.19821451, 0.16660697, 0.6189914 ],
        [0.16561335, 0.58988393, 0.46499917],
        [0.88734369, 0.05930892, 0.18737471]],

       [[0.69262855, 0.58137772, 0.24960278],
        [0.1891505 , 0.79727063, 0.23667364],
        [0.29907306, 0.66670825, 0.69498337]]])

In [136]:
# 1.3.4
arr=np.ones((3, 3), dtype=int)
arr[::1, 1] = 0
print(arr)

[[1 0 1]
 [1 0 1]
 [1 0 1]]


In [137]:
# 1.3.5
arr = np.array([randint(0, 100) for i in range(10)])
print(np.sort(arr)[::-1])

[95 90 80 34 34 33 22 12  5  1]


In [163]:
# 1.3.6
arr=np.ones((3, 3), dtype=int)
print(arr)
# число измерений (оси массива) ndarray.ndim
print(arr.ndim) # [[],[]]=2, [ [ [],[] ], [ [],[] ] ]=3
# форма (размеры массива) ndarray.shape
print(arr.shape)
# размер ndarray.size 
print(arr.size)
# тип элементов массива ndarray.dtype
print(arr.dtype)
# ndarray.itemsize - размер каждого элемента массива в байтах.
print(arr.itemsize)
# ndarray.data - буфер, содержащий фактические элементы массива.
print(arr.data)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
2
(3, 3)
9
int64
8
